// <auto-generated />
using System;
using BurgerShop.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BurgerShop.Infrastructure.Migrations
{
    [DbContext(typeof(BurgerShopDbContext))]
    [Migration("20260318195635_AddRepartoZonaIdToRendicion")]
    partial class AddRepartoZonaIdToRendicion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BurgerShop.Domain.Entities.Auth.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("integer");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RepartidorId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            NombreCompleto = "Administrador del Sistema",
                            NombreUsuario = "admin",
                            PasswordHash = "$2a$11$kU/EX5XSqZjkxGiq0vjhFOnj6.k2QosL/YfjYTAJKRMQIz9NuHWhK",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            NombreCompleto = "Operador Local",
                            NombreUsuario = "local",
                            PasswordHash = "$2a$11$0pKoaFrCbKlj/IQINhN4pumdQ550SnejahxpjBg.MLgbuTtKCufAa",
                            Rol = "Local"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            NombreCompleto = "Juan Pérez",
                            NombreUsuario = "repartidor1",
                            PasswordHash = "$2a$11$GP5TV.wofKMCcswZFsFBHOvsLJ83PqGveVQ4bcUO9FuY4V9N54Mwi",
                            RepartidorId = 1,
                            Rol = "Repartidor"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            NombreCompleto = "María García",
                            NombreUsuario = "repartidor2",
                            PasswordHash = "$2a$11$W8Sz4uInizUbeN7QyFxus.yY5OeJjg1FpWxkbaweuNyzCipCAF87u",
                            RepartidorId = 2,
                            Rol = "Repartidor"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            NombreCompleto = "Nico Flores",
                            NombreUsuario = "nico",
                            PasswordHash = "$2a$11$k8abIU/DHMapQlOJM1JCe.MsfWKeOI0UtDTfemLVgPRESrFAhYbdu",
                            RepartidorId = 3,
                            Rol = "Repartidor"
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int?>("CategoriaPadreId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SeccionCamioneta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPadreId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 17,
                            Activa = true,
                            Nombre = "Económica",
                            SeccionCamioneta = 10
                        },
                        new
                        {
                            Id = 18,
                            Activa = true,
                            Nombre = "Premium",
                            SeccionCamioneta = 10
                        },
                        new
                        {
                            Id = 1,
                            Activa = true,
                            CategoriaPadreId = 17,
                            Nombre = "Hamburguesa Económica 55gr",
                            SeccionCamioneta = 0
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            CategoriaPadreId = 17,
                            Nombre = "Hamburguesa Económica 69gr",
                            SeccionCamioneta = 0
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            CategoriaPadreId = 17,
                            Nombre = "Hamburguesa Económica 80gr",
                            SeccionCamioneta = 0
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            CategoriaPadreId = 17,
                            Nombre = "Hamburguesa Económica 110gr",
                            SeccionCamioneta = 0
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            CategoriaPadreId = 18,
                            Nombre = "Hamburguesa Premium 80gr",
                            SeccionCamioneta = 1
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            CategoriaPadreId = 18,
                            Nombre = "Hamburguesa Premium 110gr",
                            SeccionCamioneta = 1
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            CategoriaPadreId = 18,
                            Nombre = "Hamburguesa Premium 120gr",
                            SeccionCamioneta = 1
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            CategoriaPadreId = 18,
                            Nombre = "Hamburguesa Premium 160gr",
                            SeccionCamioneta = 1
                        },
                        new
                        {
                            Id = 9,
                            Activa = true,
                            CategoriaPadreId = 18,
                            Nombre = "Hamburguesa Premium 198gr",
                            SeccionCamioneta = 1
                        },
                        new
                        {
                            Id = 10,
                            Activa = true,
                            Nombre = "Salchicha Corta",
                            SeccionCamioneta = 2
                        },
                        new
                        {
                            Id = 11,
                            Activa = true,
                            Nombre = "Salchicha Larga",
                            SeccionCamioneta = 3
                        },
                        new
                        {
                            Id = 12,
                            Activa = true,
                            Nombre = "Pan Tradicional",
                            SeccionCamioneta = 4
                        },
                        new
                        {
                            Id = 13,
                            Activa = true,
                            Nombre = "Pan Maxi",
                            SeccionCamioneta = 5
                        },
                        new
                        {
                            Id = 14,
                            Activa = true,
                            Nombre = "Pan Pancho",
                            SeccionCamioneta = 6
                        },
                        new
                        {
                            Id = 15,
                            Activa = true,
                            Nombre = "Pan Super Pancho",
                            SeccionCamioneta = 7
                        },
                        new
                        {
                            Id = 16,
                            Activa = true,
                            Nombre = "Aderezos",
                            SeccionCamioneta = 8
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Combos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Media eco 69gr con pan y aderezo",
                            Nombre = "30 Hamburguesas 69gr Eco C/Pan + ADD",
                            Precio = 22000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Media eco 80gr con pan y aderezo",
                            Nombre = "30 Hamburguesas 80gr Eco C/Pan + ADD",
                            Precio = 27000m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Media eco 110gr con pan y aderezo",
                            Nombre = "20 Hamburguesas 110gr Eco C/Pan + ADD",
                            Precio = 24000m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Media premium 80gr",
                            Nombre = "30 Hamburguesas 80gr Premium C/Pan + ADD",
                            Precio = 38000m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Media premium 110gr",
                            Nombre = "20 Hamburguesas 110gr Premium C/Pan + ADD",
                            Precio = 34000m
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Media premium 120gr",
                            Nombre = "20 Hamburguesas 120gr Premium C/Pan + ADD",
                            Precio = 40000m
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "Media premium 160gr",
                            Nombre = "12 Hamburguesas 160gr Premium C/Pan + ADD",
                            Precio = 35000m
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Descripcion = "Media premium 198gr",
                            Nombre = "12 Hamburguesas 198gr Premium C/Pan + ADD",
                            Precio = 42000m
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Descripcion = "Bulto cerrado eco 69gr",
                            Nombre = "60 Hamburguesas 69gr Eco C/Pan",
                            Precio = 38000m
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Descripcion = "Bulto cerrado eco 80gr",
                            Nombre = "60 Hamburguesas 80gr Eco C/Pan",
                            Precio = 48000m
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Descripcion = "Bulto cerrado eco 110gr",
                            Nombre = "40 Hamburguesas 110gr Eco C/Pan",
                            Precio = 44000m
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Descripcion = "Bulto cerrado premium 80gr",
                            Nombre = "60 Hamburguesas 80gr Premium C/Pan",
                            Precio = 72000m
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Descripcion = "Bulto cerrado premium 110gr",
                            Nombre = "40 Hamburguesas 110gr Premium C/Pan",
                            Precio = 64000m
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Descripcion = "Bulto cerrado premium 120gr",
                            Nombre = "40 Hamburguesas 120gr Premium C/Pan",
                            Precio = 76000m
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Descripcion = "Bulto cerrado premium 160gr",
                            Nombre = "24 Hamburguesas 160gr Premium C/Pan",
                            Precio = 65000m
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Descripcion = "Bulto cerrado premium 198gr",
                            Nombre = "24 Hamburguesas 198gr Premium C/Pan",
                            Precio = 80000m
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Descripcion = "Bulto 55gr con pan tradicional",
                            Nombre = "72 Hamburguesas 55gr Eco C/Pan",
                            Precio = 32000m
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Descripcion = "Bulto 55gr sin pan ni aderezo",
                            Nombre = "72 Hamburguesas 55gr Eco S/Pan",
                            Precio = 26000m
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            Descripcion = "Media salchicha corta",
                            Nombre = "30 Panchos C/Pan + ADD",
                            Precio = 18000m
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            Descripcion = "Bulto salchicha corta",
                            Nombre = "60 Panchos C/Pan + ADD",
                            Precio = 32000m
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            Descripcion = "Media salchicha larga",
                            Nombre = "36 Super Panchos C/Pan + ADD",
                            Precio = 28000m
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            Descripcion = "Bulto salchicha larga",
                            Nombre = "60 Super Panchos C/Pan + ADD",
                            Precio = 45000m
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.ComboDetalle", b =>
                {
                    b.Property<int>("ComboId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.HasKey("ComboId", "ProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ComboDetalles");

                    b.HasData(
                        new
                        {
                            ComboId = 1,
                            ProductoId = 2,
                            Cantidad = 30
                        },
                        new
                        {
                            ComboId = 1,
                            ProductoId = 12,
                            Cantidad = 30
                        },
                        new
                        {
                            ComboId = 1,
                            ProductoId = 16,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 2,
                            ProductoId = 3,
                            Cantidad = 30
                        },
                        new
                        {
                            ComboId = 2,
                            ProductoId = 12,
                            Cantidad = 30
                        },
                        new
                        {
                            ComboId = 2,
                            ProductoId = 16,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 3,
                            ProductoId = 4,
                            Cantidad = 20
                        },
                        new
                        {
                            ComboId = 3,
                            ProductoId = 13,
                            Cantidad = 20
                        },
                        new
                        {
                            ComboId = 3,
                            ProductoId = 16,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 4,
                            ProductoId = 5,
                            Cantidad = 30
                        },
                        new
                        {
                            ComboId = 4,
                            ProductoId = 12,
                            Cantidad = 30
                        },
                        new
                        {
                            ComboId = 4,
                            ProductoId = 16,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 5,
                            ProductoId = 6,
                            Cantidad = 20
                        },
                        new
                        {
                            ComboId = 5,
                            ProductoId = 13,
                            Cantidad = 20
                        },
                        new
                        {
                            ComboId = 5,
                            ProductoId = 16,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 6,
                            ProductoId = 7,
                            Cantidad = 20
                        },
                        new
                        {
                            ComboId = 6,
                            ProductoId = 13,
                            Cantidad = 20
                        },
                        new
                        {
                            ComboId = 6,
                            ProductoId = 16,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 7,
                            ProductoId = 8,
                            Cantidad = 12
                        },
                        new
                        {
                            ComboId = 7,
                            ProductoId = 13,
                            Cantidad = 12
                        },
                        new
                        {
                            ComboId = 7,
                            ProductoId = 16,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 8,
                            ProductoId = 9,
                            Cantidad = 12
                        },
                        new
                        {
                            ComboId = 8,
                            ProductoId = 13,
                            Cantidad = 12
                        },
                        new
                        {
                            ComboId = 8,
                            ProductoId = 16,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 9,
                            ProductoId = 2,
                            Cantidad = 60
                        },
                        new
                        {
                            ComboId = 9,
                            ProductoId = 12,
                            Cantidad = 60
                        },
                        new
                        {
                            ComboId = 10,
                            ProductoId = 3,
                            Cantidad = 60
                        },
                        new
                        {
                            ComboId = 10,
                            ProductoId = 12,
                            Cantidad = 60
                        },
                        new
                        {
                            ComboId = 11,
                            ProductoId = 4,
                            Cantidad = 40
                        },
                        new
                        {
                            ComboId = 11,
                            ProductoId = 13,
                            Cantidad = 40
                        },
                        new
                        {
                            ComboId = 12,
                            ProductoId = 5,
                            Cantidad = 60
                        },
                        new
                        {
                            ComboId = 12,
                            ProductoId = 12,
                            Cantidad = 60
                        },
                        new
                        {
                            ComboId = 13,
                            ProductoId = 6,
                            Cantidad = 40
                        },
                        new
                        {
                            ComboId = 13,
                            ProductoId = 13,
                            Cantidad = 40
                        },
                        new
                        {
                            ComboId = 14,
                            ProductoId = 7,
                            Cantidad = 40
                        },
                        new
                        {
                            ComboId = 14,
                            ProductoId = 13,
                            Cantidad = 40
                        },
                        new
                        {
                            ComboId = 15,
                            ProductoId = 8,
                            Cantidad = 24
                        },
                        new
                        {
                            ComboId = 15,
                            ProductoId = 13,
                            Cantidad = 24
                        },
                        new
                        {
                            ComboId = 16,
                            ProductoId = 9,
                            Cantidad = 24
                        },
                        new
                        {
                            ComboId = 16,
                            ProductoId = 13,
                            Cantidad = 24
                        },
                        new
                        {
                            ComboId = 17,
                            ProductoId = 1,
                            Cantidad = 72
                        },
                        new
                        {
                            ComboId = 17,
                            ProductoId = 12,
                            Cantidad = 72
                        },
                        new
                        {
                            ComboId = 18,
                            ProductoId = 1,
                            Cantidad = 72
                        },
                        new
                        {
                            ComboId = 19,
                            ProductoId = 10,
                            Cantidad = 30
                        },
                        new
                        {
                            ComboId = 19,
                            ProductoId = 14,
                            Cantidad = 30
                        },
                        new
                        {
                            ComboId = 19,
                            ProductoId = 16,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 20,
                            ProductoId = 10,
                            Cantidad = 60
                        },
                        new
                        {
                            ComboId = 20,
                            ProductoId = 14,
                            Cantidad = 60
                        },
                        new
                        {
                            ComboId = 20,
                            ProductoId = 16,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 21,
                            ProductoId = 11,
                            Cantidad = 36
                        },
                        new
                        {
                            ComboId = 21,
                            ProductoId = 15,
                            Cantidad = 36
                        },
                        new
                        {
                            ComboId = 21,
                            ProductoId = 16,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 22,
                            ProductoId = 11,
                            Cantidad = 60
                        },
                        new
                        {
                            ComboId = 22,
                            ProductoId = 15,
                            Cantidad = 60
                        },
                        new
                        {
                            ComboId = 22,
                            ProductoId = 16,
                            Cantidad = 1
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.ListaPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ListasPrecios");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.ListaPrecioDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ListaPrecioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ListaPrecioId", "ProductoId")
                        .IsUnique();

                    b.ToTable("ListasPreciosDetalle");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroInterno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PesoGramos")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadesPorBulto")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadesPorMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("NumeroInterno")
                        .IsUnique();

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            Marca = "La Defensa",
                            Nombre = "Hamburguesa Eco 55gr",
                            PesoGramos = 55,
                            Precio = 300m,
                            UnidadesPorBulto = 72,
                            UnidadesPorMedia = 36
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 2,
                            Marca = "La Conquista",
                            Nombre = "Hamburguesa Eco 69gr",
                            PesoGramos = 69,
                            Precio = 450m,
                            UnidadesPorBulto = 60,
                            UnidadesPorMedia = 30
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 3,
                            Marca = "Rancho Alto",
                            Nombre = "Hamburguesa Eco 80gr",
                            PesoGramos = 80,
                            Precio = 550m,
                            UnidadesPorBulto = 60,
                            UnidadesPorMedia = 30
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 4,
                            Marca = "La Defensa",
                            Nombre = "Hamburguesa Eco 110gr",
                            PesoGramos = 110,
                            Precio = 750m,
                            UnidadesPorBulto = 40,
                            UnidadesPorMedia = 20
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 5,
                            Marca = "Finexcor",
                            Nombre = "Hamburguesa Premium 80gr",
                            PesoGramos = 80,
                            Precio = 850m,
                            UnidadesPorBulto = 60,
                            UnidadesPorMedia = 30
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaId = 6,
                            Marca = "Finexcor",
                            Nombre = "Hamburguesa Premium 110gr",
                            PesoGramos = 110,
                            Precio = 1100m,
                            UnidadesPorBulto = 40,
                            UnidadesPorMedia = 20
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaId = 7,
                            Marca = "Finexcor",
                            Nombre = "Hamburguesa Premium 120gr",
                            PesoGramos = 120,
                            Precio = 1300m,
                            UnidadesPorBulto = 40,
                            UnidadesPorMedia = 20
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaId = 8,
                            Marca = "Finexcor",
                            Nombre = "Hamburguesa Premium 160gr",
                            PesoGramos = 160,
                            Precio = 1800m,
                            UnidadesPorBulto = 24,
                            UnidadesPorMedia = 12
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CategoriaId = 9,
                            Marca = "Friar",
                            Nombre = "Hamburguesa Premium 198gr",
                            PesoGramos = 198,
                            Precio = 2200m,
                            UnidadesPorBulto = 24,
                            UnidadesPorMedia = 12
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CategoriaId = 10,
                            Marca = "Jetfood",
                            Nombre = "Salchicha Corta",
                            Precio = 350m,
                            UnidadesPorBulto = 60,
                            UnidadesPorMedia = 30
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CategoriaId = 11,
                            Marca = "Delosan",
                            Nombre = "Salchicha Larga",
                            Precio = 500m,
                            UnidadesPorBulto = 60,
                            UnidadesPorMedia = 36
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            CategoriaId = 12,
                            Nombre = "Pan Tradicional",
                            Precio = 1200m,
                            UnidadesPorBulto = 6,
                            UnidadesPorMedia = 0
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            CategoriaId = 13,
                            Nombre = "Pan Maxi",
                            Precio = 1500m,
                            UnidadesPorBulto = 6,
                            UnidadesPorMedia = 0
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            CategoriaId = 14,
                            Nombre = "Pan Pancho",
                            Precio = 1000m,
                            UnidadesPorBulto = 6,
                            UnidadesPorMedia = 0
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            CategoriaId = 15,
                            Nombre = "Pan Super Pancho",
                            Precio = 1400m,
                            UnidadesPorBulto = 6,
                            UnidadesPorMedia = 0
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            CategoriaId = 16,
                            Marca = "Benidor",
                            Nombre = "Aderezo Benidor",
                            Precio = 2500m,
                            UnidadesPorBulto = 1,
                            UnidadesPorMedia = 0
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Finanzas.CierreCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("MontoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaApertura");

                    b.ToTable("CierresCaja");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Finanzas.CierreCajaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadOperaciones")
                        .HasColumnType("integer");

                    b.Property<int>("CierreCajaId")
                        .HasColumnType("integer");

                    b.Property<int>("FormaPagoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CierreCajaId");

                    b.HasIndex("FormaPagoId");

                    b.ToTable("CierresCajaDetalle");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsDeAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Leido")
                        .HasColumnType("boolean");

                    b.Property<int>("RepartidorId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("RepartidorId");

                    b.HasIndex("RepartidorId", "Leido");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.RendicionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FormaPago")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroTicket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<int>("RendicionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("RendicionId");

                    b.ToTable("RendicionesDetalle");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.RendicionRepartidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobada")
                        .HasColumnType("boolean");

                    b.Property<int>("CantidadEntregados")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadNoEntregados")
                        .HasColumnType("integer");

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EfectivoDeclarado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RepartidorId")
                        .HasColumnType("integer");

                    b.Property<int?>("RepartoZonaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalEfectivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNoEntregado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTransferencia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("RepartidorId");

                    b.HasIndex("RepartoZonaId");

                    b.ToTable("RendicionesRepartidor");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.Repartidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoAcceso")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Vehiculo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAcceso")
                        .IsUnique();

                    b.ToTable("Repartidores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CodigoAcceso = "1234",
                            Nombre = "Juan Pérez",
                            Telefono = "11-1234-5678",
                            Vehiculo = "Moto"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CodigoAcceso = "5678",
                            Nombre = "María García",
                            Telefono = "11-8765-4321",
                            Vehiculo = "Bicicleta"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CodigoAcceso = "9999",
                            Nombre = "Nico Flores",
                            Telefono = "11-0000-0000",
                            Vehiculo = "Moto"
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.RepartidorZona", b =>
                {
                    b.Property<int>("RepartidorId")
                        .HasColumnType("integer");

                    b.Property<int>("ZonaId")
                        .HasColumnType("integer");

                    b.HasKey("RepartidorId", "ZonaId");

                    b.HasIndex("ZonaId");

                    b.ToTable("RepartidorZonas");

                    b.HasData(
                        new
                        {
                            RepartidorId = 1,
                            ZonaId = 1
                        },
                        new
                        {
                            RepartidorId = 1,
                            ZonaId = 2
                        },
                        new
                        {
                            RepartidorId = 2,
                            ZonaId = 1
                        },
                        new
                        {
                            RepartidorId = 2,
                            ZonaId = 2
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.RepartoZona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RepartidorId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCancelados")
                        .HasColumnType("integer");

                    b.Property<int>("TotalEntregados")
                        .HasColumnType("integer");

                    b.Property<int>("TotalNoEntregados")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPedidos")
                        .HasColumnType("integer");

                    b.Property<int>("ZonaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepartidorId");

                    b.HasIndex("ZonaId", "Fecha");

                    b.ToTable("RepartosZona");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.UbicacionRepartidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<int>("RepartidorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstaActivo");

                    b.HasIndex("RepartidorId")
                        .IsUnique();

                    b.ToTable("UbicacionesRepartidor");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Zonas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            CostoEnvio = 0m,
                            Nombre = "Norte"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            CostoEnvio = 0m,
                            Nombre = "Sur"
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ListaPrecioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TipoClienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("ZonaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ListaPrecioId");

                    b.HasIndex("TipoClienteId");

                    b.HasIndex("ZonaId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.FormaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PorcentajeRecargo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FormasPago");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Nombre = "Efectivo",
                            PorcentajeRecargo = 0m
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Nombre = "MercadoPago Transferencia",
                            PorcentajeRecargo = 0m
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Nombre = "Banco Galicia Débito",
                            PorcentajeRecargo = 0m
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Nombre = "Banco Galicia Crédito 1 cuota",
                            PorcentajeRecargo = 10m
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Nombre = "Banco Galicia Crédito 2 cuotas",
                            PorcentajeRecargo = 20m
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Nombre = "Banco Galicia Crédito 3 cuotas",
                            PorcentajeRecargo = 30m
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.LineaPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("ComboId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("LineasPedido");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.PagoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FormaPagoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PorcentajeRecargo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalACobrar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FormaPagoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PagosPedido");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CierreCajaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("ComprobanteEntrega")
                        .HasColumnType("text");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DireccionEntrega")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstaPago")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("FormaPagoId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NombreCliente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NotaInterna")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NotasEntrega")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NumeroTicket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("integer");

                    b.Property<int?>("RepartoZonaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TelefonoCliente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoFactura")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ZonaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CierreCajaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("FechaProgramada");

                    b.HasIndex("FormaPagoId");

                    b.HasIndex("NumeroTicket")
                        .IsUnique();

                    b.HasIndex("RepartidorId");

                    b.HasIndex("RepartoZonaId");

                    b.HasIndex("ZonaId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.TipoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposCliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Consumidor Final"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Mayorista"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Empleado"
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Auth.Usuario", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Repartidor", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Categoria", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Categoria", "CategoriaPadre")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaPadreId");

                    b.Navigation("CategoriaPadre");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Combo", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.ComboDetalle", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Combo", "Combo")
                        .WithMany("Detalles")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Producto", "Producto")
                        .WithMany("ComboDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.ListaPrecioDetalle", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.ListaPrecio", "ListaPrecio")
                        .WithMany("Detalles")
                        .HasForeignKey("ListaPrecioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ListaPrecio");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Producto", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Finanzas.CierreCajaDetalle", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Finanzas.CierreCaja", "CierreCaja")
                        .WithMany("Detalles")
                        .HasForeignKey("CierreCajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Ventas.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("FormaPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CierreCaja");

                    b.Navigation("FormaPago");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.Mensaje", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Repartidor", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.RendicionDetalle", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Ventas.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Logistica.RendicionRepartidor", "Rendicion")
                        .WithMany("Detalles")
                        .HasForeignKey("RendicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Rendicion");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.RendicionRepartidor", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Repartidor", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Logistica.RepartoZona", "RepartoZona")
                        .WithMany()
                        .HasForeignKey("RepartoZonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Repartidor");

                    b.Navigation("RepartoZona");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.RepartidorZona", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Repartidor", "Repartidor")
                        .WithMany("RepartidorZonas")
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Zona", "Zona")
                        .WithMany("RepartidorZonas")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repartidor");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.RepartoZona", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Repartidor", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repartidor");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.UbicacionRepartidor", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Repartidor", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.Cliente", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.ListaPrecio", "ListaPrecio")
                        .WithMany()
                        .HasForeignKey("ListaPrecioId");

                    b.HasOne("BurgerShop.Domain.Entities.Ventas.TipoCliente", "TipoCliente")
                        .WithMany()
                        .HasForeignKey("TipoClienteId");

                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId");

                    b.Navigation("ListaPrecio");

                    b.Navigation("TipoCliente");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.LineaPedido", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId");

                    b.HasOne("BurgerShop.Domain.Entities.Ventas.Pedido", "Pedido")
                        .WithMany("Lineas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.Navigation("Combo");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.PagoPedido", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Ventas.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("FormaPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Ventas.Pedido", "Pedido")
                        .WithMany("Pagos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaPago");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.Pedido", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Finanzas.CierreCaja", "CierreCaja")
                        .WithMany("Pedidos")
                        .HasForeignKey("CierreCajaId");

                    b.HasOne("BurgerShop.Domain.Entities.Ventas.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId");

                    b.HasOne("BurgerShop.Domain.Entities.Ventas.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("FormaPagoId");

                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Repartidor", "Repartidor")
                        .WithMany("Pedidos")
                        .HasForeignKey("RepartidorId");

                    b.HasOne("BurgerShop.Domain.Entities.Logistica.RepartoZona", "RepartoZona")
                        .WithMany()
                        .HasForeignKey("RepartoZonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId");

                    b.Navigation("CierreCaja");

                    b.Navigation("Cliente");

                    b.Navigation("FormaPago");

                    b.Navigation("Repartidor");

                    b.Navigation("RepartoZona");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Categoria", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Combo", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.ListaPrecio", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Producto", b =>
                {
                    b.Navigation("ComboDetalles");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Finanzas.CierreCaja", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.RendicionRepartidor", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.Repartidor", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("RepartidorZonas");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.Zona", b =>
                {
                    b.Navigation("RepartidorZonas");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.Pedido", b =>
                {
                    b.Navigation("Lineas");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
