// <auto-generated />
using System;
using BurgerShop.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BurgerShop.Infrastructure.Migrations
{
    [DbContext(typeof(BurgerShopDbContext))]
    partial class BurgerShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("BurgerShop.Domain.Entities.Auth.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RepartidorId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            NombreCompleto = "Administrador del Sistema",
                            NombreUsuario = "admin",
                            PasswordHash = "$2a$11$kU/EX5XSqZjkxGiq0vjhFOnj6.k2QosL/YfjYTAJKRMQIz9NuHWhK",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            NombreCompleto = "Operador Local",
                            NombreUsuario = "local",
                            PasswordHash = "$2a$11$0pKoaFrCbKlj/IQINhN4pumdQ550SnejahxpjBg.MLgbuTtKCufAa",
                            Rol = "Local"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            NombreCompleto = "Juan Pérez",
                            NombreUsuario = "repartidor1",
                            PasswordHash = "$2a$11$GP5TV.wofKMCcswZFsFBHOvsLJ83PqGveVQ4bcUO9FuY4V9N54Mwi",
                            RepartidorId = 1,
                            Rol = "Repartidor"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            NombreCompleto = "María García",
                            NombreUsuario = "repartidor2",
                            PasswordHash = "$2a$11$W8Sz4uInizUbeN7QyFxus.yY5OeJjg1FpWxkbaweuNyzCipCAF87u",
                            RepartidorId = 2,
                            Rol = "Repartidor"
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeccionCamioneta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Nombre = "Hamburguesas",
                            SeccionCamioneta = 0
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Nombre = "Maxi Hamburguesas",
                            SeccionCamioneta = 1
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Nombre = "Super Hamburguesas",
                            SeccionCamioneta = 1
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Nombre = "Mega Hamburguesas",
                            SeccionCamioneta = 1
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Nombre = "Pan Hamburguesa",
                            SeccionCamioneta = 4
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Nombre = "Pan Maxi Hamburguesa",
                            SeccionCamioneta = 5
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            Nombre = "Panchos",
                            SeccionCamioneta = 2
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            Nombre = "Salchichas",
                            SeccionCamioneta = 2
                        },
                        new
                        {
                            Id = 9,
                            Activa = true,
                            Nombre = "Pan Pancho",
                            SeccionCamioneta = 6
                        },
                        new
                        {
                            Id = 10,
                            Activa = true,
                            Nombre = "Super Panchos",
                            SeccionCamioneta = 3
                        },
                        new
                        {
                            Id = 11,
                            Activa = true,
                            Nombre = "Salchichas Largas",
                            SeccionCamioneta = 3
                        },
                        new
                        {
                            Id = 12,
                            Activa = true,
                            Nombre = "Pan Super Pancho",
                            SeccionCamioneta = 7
                        },
                        new
                        {
                            Id = 13,
                            Activa = true,
                            Nombre = "Aderezos",
                            SeccionCamioneta = 8
                        },
                        new
                        {
                            Id = 14,
                            Activa = true,
                            Nombre = "Snacks",
                            SeccionCamioneta = 9
                        },
                        new
                        {
                            Id = 15,
                            Activa = true,
                            Nombre = "Congelados",
                            SeccionCamioneta = 9
                        },
                        new
                        {
                            Id = 16,
                            Activa = true,
                            Nombre = "Bebidas",
                            SeccionCamioneta = 9
                        },
                        new
                        {
                            Id = 17,
                            Activa = true,
                            Nombre = "Ofertas Semanales",
                            SeccionCamioneta = 10
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Combos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 17,
                            Descripcion = "40 hamburguesas 110gr + 40 panes",
                            Nombre = "Promo 40 Hamburguesas + Pan",
                            Precio = 3700m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 17,
                            Descripcion = "30 hamburguesas 69gr + 30 panes",
                            Nombre = "Promo 30 Hamburguesas + Pan",
                            Precio = 2700m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 17,
                            Descripcion = "30 panchos + 30 panes",
                            Nombre = "Promo 30 Panchos",
                            Precio = 1900m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 17,
                            Descripcion = "18 super panchos + 18 panes",
                            Nombre = "Promo 18 Super Panchos",
                            Precio = 1600m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 17,
                            Descripcion = "36 super panchos + 36 panes",
                            Nombre = "Promo 36 Super Panchos",
                            Precio = 2950m
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.ComboDetalle", b =>
                {
                    b.Property<int>("ComboId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComboId", "ProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ComboDetalles");

                    b.HasData(
                        new
                        {
                            ComboId = 1,
                            ProductoId = 6,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 1,
                            ProductoId = 23,
                            Cantidad = 2
                        },
                        new
                        {
                            ComboId = 2,
                            ProductoId = 5,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 2,
                            ProductoId = 23,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 3,
                            ProductoId = 29,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 3,
                            ProductoId = 27,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 3,
                            ProductoId = 33,
                            Cantidad = 2
                        },
                        new
                        {
                            ComboId = 4,
                            ProductoId = 34,
                            Cantidad = 3
                        },
                        new
                        {
                            ComboId = 4,
                            ProductoId = 38,
                            Cantidad = 3
                        },
                        new
                        {
                            ComboId = 5,
                            ProductoId = 35,
                            Cantidad = 3
                        },
                        new
                        {
                            ComboId = 5,
                            ProductoId = 39,
                            Cantidad = 3
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.ListaPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ListasPrecios");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.ListaPrecioDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListaPrecioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ListaPrecioId", "ProductoId")
                        .IsUnique();

                    b.ToTable("ListasPreciosDetalle");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroInterno")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PesoGramos")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadesPorBulto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("NumeroInterno")
                        .IsUnique();

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            Nombre = "Hamburguesa x 1",
                            NumeroInterno = "HAM-001",
                            PesoGramos = 80,
                            Precio = 50m,
                            UnidadesPorBulto = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 1,
                            Nombre = "Hamburguesa x 2",
                            NumeroInterno = "HAM-002",
                            PesoGramos = 80,
                            Precio = 100m,
                            UnidadesPorBulto = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 1,
                            Nombre = "Hamburguesa x 6",
                            NumeroInterno = "HAM-003",
                            PesoGramos = 80,
                            Precio = 250m,
                            UnidadesPorBulto = 6
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 1,
                            Nombre = "Hamburguesa x 12",
                            NumeroInterno = "HAM-004",
                            PesoGramos = 80,
                            Precio = 400m,
                            UnidadesPorBulto = 12
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 1,
                            Nombre = "Hamburguesa x 30",
                            NumeroInterno = "HAM-005",
                            PesoGramos = 80,
                            Precio = 750m,
                            UnidadesPorBulto = 30
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaId = 1,
                            Nombre = "Hamburguesa x 40",
                            NumeroInterno = "HAM-006",
                            PesoGramos = 80,
                            Precio = 940m,
                            UnidadesPorBulto = 40
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaId = 2,
                            Nombre = "Maxi Hamburguesa x 1",
                            NumeroInterno = "MAX-001",
                            PesoGramos = 110,
                            Precio = 70m,
                            UnidadesPorBulto = 1
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaId = 2,
                            Nombre = "Maxi Hamburguesa x 2",
                            NumeroInterno = "MAX-002",
                            PesoGramos = 110,
                            Precio = 130m,
                            UnidadesPorBulto = 2
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CategoriaId = 2,
                            Nombre = "Maxi Hamburguesa x 4",
                            NumeroInterno = "MAX-003",
                            PesoGramos = 110,
                            Precio = 260m,
                            UnidadesPorBulto = 4
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CategoriaId = 2,
                            Nombre = "Maxi Hamburguesa x 12",
                            NumeroInterno = "MAX-004",
                            PesoGramos = 110,
                            Precio = 680m,
                            UnidadesPorBulto = 12
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CategoriaId = 2,
                            Nombre = "Maxi Hamburguesa x 20",
                            NumeroInterno = "MAX-005",
                            PesoGramos = 110,
                            Precio = 1100m,
                            UnidadesPorBulto = 20
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            CategoriaId = 3,
                            Nombre = "Super Hamburguesa x 1",
                            NumeroInterno = "SUP-001",
                            PesoGramos = 120,
                            Precio = 100m,
                            UnidadesPorBulto = 1
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            CategoriaId = 3,
                            Nombre = "Super Hamburguesa x 2",
                            NumeroInterno = "SUP-002",
                            PesoGramos = 120,
                            Precio = 180m,
                            UnidadesPorBulto = 2
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            CategoriaId = 3,
                            Nombre = "Super Hamburguesa x 4",
                            NumeroInterno = "SUP-003",
                            PesoGramos = 120,
                            Precio = 350m,
                            UnidadesPorBulto = 4
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            CategoriaId = 3,
                            Nombre = "Super Hamburguesa x 12",
                            NumeroInterno = "SUP-004",
                            PesoGramos = 120,
                            Precio = 1000m,
                            UnidadesPorBulto = 12
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            CategoriaId = 4,
                            Nombre = "Mega Hamburguesa x 1",
                            NumeroInterno = "MEG-001",
                            PesoGramos = 160,
                            Precio = 120m,
                            UnidadesPorBulto = 1
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            CategoriaId = 4,
                            Nombre = "Mega Hamburguesa x 2",
                            NumeroInterno = "MEG-002",
                            PesoGramos = 160,
                            Precio = 220m,
                            UnidadesPorBulto = 2
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            CategoriaId = 4,
                            Nombre = "Mega Hamburguesa x 4",
                            NumeroInterno = "MEG-003",
                            PesoGramos = 160,
                            Precio = 420m,
                            UnidadesPorBulto = 4
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            CategoriaId = 4,
                            Nombre = "Mega Hamburguesa x 12",
                            NumeroInterno = "MEG-004",
                            PesoGramos = 160,
                            Precio = 1200m,
                            UnidadesPorBulto = 12
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            CategoriaId = 5,
                            Nombre = "Pan Hamburguesa x 2",
                            NumeroInterno = "PHA-001",
                            Precio = 80m,
                            UnidadesPorBulto = 2
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            CategoriaId = 5,
                            Nombre = "Pan Hamburguesa x 6",
                            NumeroInterno = "PHA-002",
                            Precio = 200m,
                            UnidadesPorBulto = 6
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            CategoriaId = 5,
                            Nombre = "Pan Hamburguesa x 12",
                            NumeroInterno = "PHA-003",
                            Precio = 360m,
                            UnidadesPorBulto = 12
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            CategoriaId = 5,
                            Nombre = "Pan Hamburguesa x 30",
                            NumeroInterno = "PHA-004",
                            Precio = 800m,
                            UnidadesPorBulto = 30
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            CategoriaId = 6,
                            Nombre = "Pan Maxi x 2",
                            NumeroInterno = "PMA-001",
                            Precio = 100m,
                            UnidadesPorBulto = 2
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            CategoriaId = 6,
                            Nombre = "Pan Maxi x 6",
                            NumeroInterno = "PMA-002",
                            Precio = 260m,
                            UnidadesPorBulto = 6
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            CategoriaId = 6,
                            Nombre = "Pan Maxi x 12",
                            NumeroInterno = "PMA-003",
                            Precio = 480m,
                            UnidadesPorBulto = 12
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            CategoriaId = 7,
                            Nombre = "Pancho x 6",
                            NumeroInterno = "PAN-001",
                            Precio = 150m,
                            UnidadesPorBulto = 6
                        },
                        new
                        {
                            Id = 28,
                            Activo = true,
                            CategoriaId = 7,
                            Nombre = "Pancho x 12",
                            NumeroInterno = "PAN-002",
                            Precio = 260m,
                            UnidadesPorBulto = 12
                        },
                        new
                        {
                            Id = 29,
                            Activo = true,
                            CategoriaId = 7,
                            Nombre = "Pancho x 24",
                            NumeroInterno = "PAN-003",
                            Precio = 480m,
                            UnidadesPorBulto = 24
                        },
                        new
                        {
                            Id = 30,
                            Activo = true,
                            CategoriaId = 8,
                            Nombre = "Salchicha x 6",
                            NumeroInterno = "SAL-001",
                            Precio = 180m,
                            UnidadesPorBulto = 6
                        },
                        new
                        {
                            Id = 31,
                            Activo = true,
                            CategoriaId = 8,
                            Nombre = "Salchicha x 12",
                            NumeroInterno = "SAL-002",
                            Precio = 320m,
                            UnidadesPorBulto = 12
                        },
                        new
                        {
                            Id = 32,
                            Activo = true,
                            CategoriaId = 9,
                            Nombre = "Pan Pancho x 6",
                            NumeroInterno = "PPH-001",
                            Precio = 100m,
                            UnidadesPorBulto = 6
                        },
                        new
                        {
                            Id = 33,
                            Activo = true,
                            CategoriaId = 9,
                            Nombre = "Pan Pancho x 12",
                            NumeroInterno = "PPH-002",
                            Precio = 180m,
                            UnidadesPorBulto = 12
                        },
                        new
                        {
                            Id = 34,
                            Activo = true,
                            CategoriaId = 10,
                            Nombre = "Super Pancho x 6",
                            NumeroInterno = "SPC-001",
                            Precio = 200m,
                            UnidadesPorBulto = 6
                        },
                        new
                        {
                            Id = 35,
                            Activo = true,
                            CategoriaId = 10,
                            Nombre = "Super Pancho x 12",
                            NumeroInterno = "SPC-002",
                            Precio = 380m,
                            UnidadesPorBulto = 12
                        },
                        new
                        {
                            Id = 36,
                            Activo = true,
                            CategoriaId = 11,
                            Nombre = "Salchicha Larga x 6",
                            NumeroInterno = "SLA-001",
                            Precio = 220m,
                            UnidadesPorBulto = 6
                        },
                        new
                        {
                            Id = 37,
                            Activo = true,
                            CategoriaId = 11,
                            Nombre = "Salchicha Larga x 12",
                            NumeroInterno = "SLA-002",
                            Precio = 400m,
                            UnidadesPorBulto = 12
                        },
                        new
                        {
                            Id = 38,
                            Activo = true,
                            CategoriaId = 12,
                            Nombre = "Pan Super Pancho x 6",
                            NumeroInterno = "PSP-001",
                            Precio = 130m,
                            UnidadesPorBulto = 6
                        },
                        new
                        {
                            Id = 39,
                            Activo = true,
                            CategoriaId = 12,
                            Nombre = "Pan Super Pancho x 12",
                            NumeroInterno = "PSP-002",
                            Precio = 240m,
                            UnidadesPorBulto = 12
                        },
                        new
                        {
                            Id = 40,
                            Activo = true,
                            CategoriaId = 13,
                            Nombre = "Mayonesa",
                            NumeroInterno = "ADR-001",
                            Precio = 80m,
                            UnidadesPorBulto = 1
                        },
                        new
                        {
                            Id = 41,
                            Activo = true,
                            CategoriaId = 13,
                            Nombre = "Ketchup",
                            NumeroInterno = "ADR-002",
                            Precio = 80m,
                            UnidadesPorBulto = 1
                        },
                        new
                        {
                            Id = 42,
                            Activo = true,
                            CategoriaId = 13,
                            Nombre = "Mostaza",
                            NumeroInterno = "ADR-003",
                            Precio = 80m,
                            UnidadesPorBulto = 1
                        },
                        new
                        {
                            Id = 43,
                            Activo = true,
                            CategoriaId = 14,
                            Nombre = "Papas Congeladas x 1kg",
                            NumeroInterno = "SNK-001",
                            Precio = 300m,
                            UnidadesPorBulto = 1
                        },
                        new
                        {
                            Id = 44,
                            Activo = true,
                            CategoriaId = 15,
                            Nombre = "Empanadas x 12",
                            NumeroInterno = "CON-001",
                            Precio = 500m,
                            UnidadesPorBulto = 12
                        },
                        new
                        {
                            Id = 45,
                            Activo = true,
                            CategoriaId = 15,
                            Nombre = "Milanesas x 4",
                            NumeroInterno = "CON-002",
                            Precio = 450m,
                            UnidadesPorBulto = 4
                        },
                        new
                        {
                            Id = 46,
                            Activo = true,
                            CategoriaId = 16,
                            Nombre = "Coca Cola 1.5L",
                            NumeroInterno = "BEB-001",
                            Precio = 200m,
                            UnidadesPorBulto = 1
                        },
                        new
                        {
                            Id = 47,
                            Activo = true,
                            CategoriaId = 16,
                            Nombre = "Sprite 1.5L",
                            NumeroInterno = "BEB-002",
                            Precio = 200m,
                            UnidadesPorBulto = 1
                        },
                        new
                        {
                            Id = 48,
                            Activo = true,
                            CategoriaId = 16,
                            Nombre = "Agua 500ml",
                            NumeroInterno = "BEB-003",
                            Precio = 100m,
                            UnidadesPorBulto = 1
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Finanzas.CierreCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MontoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaApertura");

                    b.ToTable("CierresCaja");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Finanzas.CierreCajaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadOperaciones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CierreCajaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormaPagoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CierreCajaId");

                    b.HasIndex("FormaPagoId");

                    b.ToTable("CierresCajaDetalle");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.Repartidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoAcceso")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vehiculo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAcceso")
                        .IsUnique();

                    b.ToTable("Repartidores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CodigoAcceso = "1234",
                            Nombre = "Juan Pérez",
                            Telefono = "11-1234-5678",
                            Vehiculo = "Moto"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CodigoAcceso = "5678",
                            Nombre = "María García",
                            Telefono = "11-8765-4321",
                            Vehiculo = "Bicicleta"
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.RepartidorZona", b =>
                {
                    b.Property<int>("RepartidorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RepartidorId", "ZonaId");

                    b.HasIndex("ZonaId");

                    b.ToTable("RepartidorZonas");

                    b.HasData(
                        new
                        {
                            RepartidorId = 1,
                            ZonaId = 1
                        },
                        new
                        {
                            RepartidorId = 1,
                            ZonaId = 2
                        },
                        new
                        {
                            RepartidorId = 2,
                            ZonaId = 1
                        },
                        new
                        {
                            RepartidorId = 2,
                            ZonaId = 2
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zonas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            CostoEnvio = 0m,
                            Nombre = "Norte"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            CostoEnvio = 0m,
                            Nombre = "Sur"
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ListaPrecioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TipoClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ZonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ListaPrecioId");

                    b.HasIndex("TipoClienteId");

                    b.HasIndex("ZonaId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.FormaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcentajeRecargo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FormasPago");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Nombre = "Efectivo",
                            PorcentajeRecargo = 0m
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Nombre = "MercadoPago Transferencia",
                            PorcentajeRecargo = 0m
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Nombre = "Banco Galicia Débito",
                            PorcentajeRecargo = 0m
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Nombre = "Banco Galicia Crédito 1 cuota",
                            PorcentajeRecargo = 10m
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Nombre = "Banco Galicia Crédito 2 cuotas",
                            PorcentajeRecargo = 20m
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Nombre = "Banco Galicia Crédito 3 cuotas",
                            PorcentajeRecargo = 30m
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.LineaPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComboId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("LineasPedido");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.PagoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormaPagoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeRecargo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalACobrar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FormaPagoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PagosPedido");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CierreCajaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DireccionEntrega")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaPago")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FormaPagoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCliente")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotaInterna")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotasEntrega")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTicket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TelefonoCliente")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoFactura")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ZonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CierreCajaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("FechaProgramada");

                    b.HasIndex("FormaPagoId");

                    b.HasIndex("NumeroTicket")
                        .IsUnique();

                    b.HasIndex("RepartidorId");

                    b.HasIndex("ZonaId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.TipoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposCliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Consumidor Final"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Mayorista"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Empleado"
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Auth.Usuario", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Repartidor", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Combo", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.ComboDetalle", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Combo", "Combo")
                        .WithMany("Detalles")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Producto", "Producto")
                        .WithMany("ComboDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.ListaPrecioDetalle", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.ListaPrecio", "ListaPrecio")
                        .WithMany("Detalles")
                        .HasForeignKey("ListaPrecioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ListaPrecio");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Producto", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Finanzas.CierreCajaDetalle", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Finanzas.CierreCaja", "CierreCaja")
                        .WithMany("Detalles")
                        .HasForeignKey("CierreCajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Ventas.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("FormaPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CierreCaja");

                    b.Navigation("FormaPago");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.RepartidorZona", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Repartidor", "Repartidor")
                        .WithMany("RepartidorZonas")
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Zona", "Zona")
                        .WithMany("RepartidorZonas")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repartidor");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.Cliente", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.ListaPrecio", "ListaPrecio")
                        .WithMany()
                        .HasForeignKey("ListaPrecioId");

                    b.HasOne("BurgerShop.Domain.Entities.Ventas.TipoCliente", "TipoCliente")
                        .WithMany()
                        .HasForeignKey("TipoClienteId");

                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId");

                    b.Navigation("ListaPrecio");

                    b.Navigation("TipoCliente");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.LineaPedido", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId");

                    b.HasOne("BurgerShop.Domain.Entities.Ventas.Pedido", "Pedido")
                        .WithMany("Lineas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Catalogo.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.Navigation("Combo");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.PagoPedido", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Ventas.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("FormaPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Ventas.Pedido", "Pedido")
                        .WithMany("Pagos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaPago");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.Pedido", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Finanzas.CierreCaja", "CierreCaja")
                        .WithMany("Pedidos")
                        .HasForeignKey("CierreCajaId");

                    b.HasOne("BurgerShop.Domain.Entities.Ventas.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId");

                    b.HasOne("BurgerShop.Domain.Entities.Ventas.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("FormaPagoId");

                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Repartidor", "Repartidor")
                        .WithMany("Pedidos")
                        .HasForeignKey("RepartidorId");

                    b.HasOne("BurgerShop.Domain.Entities.Logistica.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId");

                    b.Navigation("CierreCaja");

                    b.Navigation("Cliente");

                    b.Navigation("FormaPago");

                    b.Navigation("Repartidor");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Combo", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.ListaPrecio", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Catalogo.Producto", b =>
                {
                    b.Navigation("ComboDetalles");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Finanzas.CierreCaja", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.Repartidor", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("RepartidorZonas");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Logistica.Zona", b =>
                {
                    b.Navigation("RepartidorZonas");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Ventas.Pedido", b =>
                {
                    b.Navigation("Lineas");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
