// <auto-generated />
using System;
using BurgerShop.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BurgerShop.Infrastructure.Migrations
{
    [DbContext(typeof(BurgerShopDbContext))]
    partial class BurgerShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("BurgerShop.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Nombre = "Hamburguesas"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Nombre = "Bebidas"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Nombre = "Acompañamientos"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Nombre = "Postres"
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ZonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Combos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Hamburguesa Clásica + Papas + Coca-Cola",
                            Nombre = "Combo Clásico",
                            Precio = 6000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Hamburguesa Doble + Papas + Coca-Cola",
                            Nombre = "Combo Doble",
                            Precio = 7500m
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.ComboDetalle", b =>
                {
                    b.Property<int>("ComboId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComboId", "ProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ComboDetalles");

                    b.HasData(
                        new
                        {
                            ComboId = 1,
                            ProductoId = 1,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 1,
                            ProductoId = 6,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 1,
                            ProductoId = 4,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 2,
                            ProductoId = 2,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 2,
                            ProductoId = 6,
                            Cantidad = 1
                        },
                        new
                        {
                            ComboId = 2,
                            ProductoId = 4,
                            Cantidad = 1
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.LineaPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComboId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("LineasPedido");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DireccionEntrega")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotasEntrega")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTicket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TelefonoCliente")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ZonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("NumeroTicket")
                        .IsUnique();

                    b.HasIndex("RepartidorId");

                    b.HasIndex("ZonaId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "Carne, lechuga, tomate, queso",
                            Nombre = "Hamburguesa Clásica",
                            Precio = 3500m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "Doble carne, doble queso",
                            Nombre = "Hamburguesa Doble",
                            Precio = 5000m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "Carne, bacon, queso cheddar",
                            Nombre = "Hamburguesa Bacon",
                            Precio = 4500m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 2,
                            Nombre = "Coca-Cola 500ml",
                            Precio = 1500m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 2,
                            Nombre = "Agua Mineral 500ml",
                            Precio = 1000m
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaId = 3,
                            Descripcion = "Porción grande",
                            Nombre = "Papas Fritas",
                            Precio = 2000m
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaId = 3,
                            Descripcion = "Porción de 8 unidades",
                            Nombre = "Aros de Cebolla",
                            Precio = 2500m
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaId = 4,
                            Descripcion = "Brownie de chocolate con nuez",
                            Nombre = "Brownie",
                            Precio = 2000m
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Repartidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoAcceso")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vehiculo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAcceso")
                        .IsUnique();

                    b.ToTable("Repartidores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CodigoAcceso = "1234",
                            Nombre = "Juan Pérez",
                            Telefono = "11-1234-5678",
                            Vehiculo = "Moto"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CodigoAcceso = "5678",
                            Nombre = "María García",
                            Telefono = "11-8765-4321",
                            Vehiculo = "Bicicleta"
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.RepartidorZona", b =>
                {
                    b.Property<int>("RepartidorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RepartidorId", "ZonaId");

                    b.HasIndex("ZonaId");

                    b.ToTable("RepartidorZonas");

                    b.HasData(
                        new
                        {
                            RepartidorId = 1,
                            ZonaId = 1
                        },
                        new
                        {
                            RepartidorId = 1,
                            ZonaId = 2
                        },
                        new
                        {
                            RepartidorId = 2,
                            ZonaId = 1
                        },
                        new
                        {
                            RepartidorId = 2,
                            ZonaId = 3
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zonas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            CostoEnvio = 500m,
                            Descripcion = "Zona céntrica",
                            Nombre = "Centro"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            CostoEnvio = 800m,
                            Descripcion = "Zona norte",
                            Nombre = "Norte"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            CostoEnvio = 800m,
                            Descripcion = "Zona sur",
                            Nombre = "Sur"
                        });
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.ComboDetalle", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Combo", "Combo")
                        .WithMany("Detalles")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Producto", "Producto")
                        .WithMany("ComboDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.LineaPedido", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId");

                    b.HasOne("BurgerShop.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Lineas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.Navigation("Combo");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId");

                    b.HasOne("BurgerShop.Domain.Entities.Repartidor", "Repartidor")
                        .WithMany("Pedidos")
                        .HasForeignKey("RepartidorId");

                    b.HasOne("BurgerShop.Domain.Entities.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId");

                    b.Navigation("Cliente");

                    b.Navigation("Repartidor");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Producto", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.RepartidorZona", b =>
                {
                    b.HasOne("BurgerShop.Domain.Entities.Repartidor", "Repartidor")
                        .WithMany("RepartidorZonas")
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerShop.Domain.Entities.Zona", "Zona")
                        .WithMany("RepartidorZonas")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repartidor");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Combo", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Producto", b =>
                {
                    b.Navigation("ComboDetalles");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Repartidor", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("RepartidorZonas");
                });

            modelBuilder.Entity("BurgerShop.Domain.Entities.Zona", b =>
                {
                    b.Navigation("RepartidorZonas");
                });
#pragma warning restore 612, 618
        }
    }
}
